name: Deploy to Server

on:
  push:
    branches: [ main ] # Change to master if your default branch is named master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and update code
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          timeout: 60s
          command_timeout: 10m
          script: |
            cd /root/Beas-Leave-Management
            git pull origin main
            npm install
            npm run build
            pm2 restart all